### PR TITLE
Add Ben Hutton to regular members list

### PR DESCRIPTION
**Pull request by Relequestual**
I was invited to add myself to the regular members list. I'm the project lead for the JSON Schema org.
I am active in the OpenJS Foundation slack, submitted PRs, and sparked discussions for the CPC. I am here to serve the open source community.

Signed-off-by: Ben Hutton <relequestual@gmail.com>

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
Wholeheartedly approve. :)

**Review by ljharb — APPROVED** [review]

**Review by eemeli — APPROVED** [review]

**Review by tobie — APPROVED** [review]

**Review by ovflowd — APPROVED** [review]
+1

**Comment by joesepi** [comment]
Hey @Relequestual -- we will merge this soon. I just want to get the process updated and good for this PR and moving forward. (Adding to teams and email lists and such.) THANKS!

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Review by erickzhao — APPROVED** [review]

**Pull request merged**
