### PR TITLE
Convert project list to table of links

### PR DESCRIPTION
**Pull request by knolleary**
As proposed in #630, this PR converts the list of projects into a table of links.

Where a project has artwork in the [artwork](https://github.com/openjs-foundation/artwork) repo, I have used that.

I have tried to identify the appropriate Contributing and CoC links for each project - some I could not find so have left blank.

I noticed that Globalize was missing from the list, so have added it back in. Jed is listed in the artwork repo, but was not in the readme, but nor is it on the [Hosted Projects page](https://openjsf.org/projects/) so I have left it off for now.

I no longer enjoy Markdown tables.

Here's a direct link to the rendered version for ease of review... https://github.com/knolleary/cross-project-council/blob/project-table/README.md

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Looks good but any reason we don't have some of the links to the charters like the one for `node.js`?

**Comment by knolleary** [comment]
> any reason we don't have some of the links to the charters like the one for node.js?

In absence of a standard way for projects to share their charter, I wasn't sure which projects had one and which didn't. Having gone through all of the repos to dig out contrib and coc links, I figured this was a good start and we can either update in subsequent prs, or if anyone can drop links to relevant charters I'll get them added.

**Review by sendilkumarn — APPROVED** [review]

**Review by christian-bromann — APPROVED** [review]

**Comment by mhdawson** [comment]
Node actually has 2 chaters:

https://github.com/nodejs/TSC/blob/master/TSC-Charter.md
https://github.com/nodejs/community-committee/blob/master/Community-Committee-Charter.md

**Review by tobie — CHANGES_REQUESTED** [review]
Thanks for doing this and sorry for being the party pooper, here, but I'm concerned about the accessibility of this data. I have the two following suggestions (with the caveat that I am not an accessibility expert):

1. Add an alt attribute to images (with something along the lines of "logo of project Foo").
2. Replace "🔗" with the actual name of the document that is being linked.

**Comment by knolleary** [comment]
@tobie good suggestions -have updated the table accordingly.

**Review by kborchers — APPROVED** [review]

**Review by tobie — APPROVED** [review]
Thanks! <3

**Review by dmethvin — APPROVED** [review]

**Review by joesepi — APPROVED** [review]
🎉

**Comment by eemeli** [comment]
> Jed is listed in the artwork repo, but was not in the readme, but nor is it on the [Hosted Projects page](https://openjsf.org/projects/) so I have left it off for now.

My understanding is that while Jed and messageformat were separate projects of the JS Foundation, Jed is considered to have been folded into messageformat during the OpenJS transition; its current repo is [messageformat/Jed](https://github.com/messageformat/Jed). I think @jorydotcom can verify/correct this?

**Review by eemeli — APPROVED** [review]

**Comment by eemeli** [comment]
Would it be easier/desirable to keep the source data e.g. in a YAML file, and to generate the markdown table from that with a script? I'd be happy to write it if we want.

**Comment by joesepi** [comment]
Let's land this and then address any updates or tweaks. Even though I hate YAML, I think a different format would be nicer.

**Pull request merged**
