### PR TITLE
Fix https -> http link for nvm

### PR DESCRIPTION
**Pull request by kborchers**

### CODE REVIEW

**Comment by kborchers** [comment]
Requesting fast track approval

**Comment by kborchers** [comment]
With 2 fast track and 2 review approvals I will land this PR. Thanks!

**Comment by ChALkeR** [comment]
A better solution would be for nvm.sh to enable https support...

**Comment by brianwarner** [comment]
Assuming everything proceeds through the process, SSL forwarding is something which the Foundation can provide for managed domains.

In the meantime @ljharb, if it would be helpful I can offer some pointers in setting up Let's Encrypt for a forwarding-only domain.  Catch me on Slack if I can help.

**Pull request merged**
