### PR TITLE
doc: used HEAD to refer to primary branch

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
thanks!

**Review by joesepi — APPROVED** [review]
THANK YOU!!

**Review by MylesBorins — APPROVED** [review]
LGTM

**Review by codebytere — APPROVED** [review]

**Review by eemeli — APPROVED** [review]

**Comment by mhdawson** [comment]
oops, I did not notice that https://github.com/openjs-foundation/cross-project-council/pull/716 was already open...

**Comment by mhdawson** [comment]
Closing as duplicated of https://github.com/openjs-foundation/cross-project-council/pull/716

**Pull request closed without merging**
