### PR TITLE
Travel fund request for Collab Summit - Dublin

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Travel Fund request for Collab Summit + NodeConfEU
Dates: 29 Sept - 6 Oct
Traveling from: Berlin
Flight: 186 USD
Hotel: 800 USD (550 + 250)
Visa: 60 USD
Local transport: 100 USD (to/from Dublin and Kilkenny to the conference venue. Hopefully this will be less.)
Event Ticket: 679 USD
Total: 1825 USD

I couldn't get funding from my employer.

I've added an extra row at the bottom with the total of all approved funds + this one. Easy to keep track of. It should be updated with every new request. If others don't agree, I can remove it.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ljharb — APPROVED** [review]

**Review by Trott — APPROVED** [review]
We're OK paying for NodeConf EU tickets even though it's in another city etc.? (I'm OK with it. Just making sure others are!)

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by bnb — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
+ 136 USD (Total 1825)

The hotel and flight prices went up in the last few days.
I've booked the flight and reserved the hotel as I'm sure I'll make the trip anyway.

Please re-approve everyone. 🙇

**Review by bnb — APPROVED** [review]

**Comment by bnb** [comment]
IMO if the hotel prices change again before the necessary approvals arrive, just ship it and adjust when you submit.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by Trott** [comment]
> We're OK paying for NodeConf EU tickets even though it's in another city, isn't tied to the collab summit other than via convenience of timing, etc.? (I'm OK with it. Just making sure others are!)

@openjs-foundation/cpc Can we get a definitive affirmation that conforms with policy?

**Review by Trott — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
@ljharb @mcollina can one of you re-approve?

@Trott should we wait for response from cpc? Or can this be merged?

**Review by ljharb — APPROVED** [review]

**Comment by Trott** [comment]
> @ljharb @mcollina can one of you re-approve?
> 
> @Trott should we wait for response from cpc? Or can this be merged?

The [travel fund doc](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/project-resources/MEMBER_TRAVEL_FUND.md#considerations-for-approval-of-a-request) says:

> Preference is given to events hosted or sponsored by the OpenJS Foundation.

If preference is given to events hosted or sponsored by the OpenJS Foundation, then events *not* hosted or sponsored by the OpenJS Foundation must be eligible. So given that we have no one weighing in with a contrary opinion and that this has sufficient approval, I think it would be fine to merge it.

**Pull request merged**
