### PR TITLE
Add Ian Sutherland to 2022 travel fund

### PR DESCRIPTION
**Pull request by iansu**
Making a travel fund request for OpenJS World 2022 to attend the conference and collaborator summit. I am hoping to help facilitate the Tooling Group sessions at the collab summit. I am also speaking at the event but virtually.

**Costs**
Hotel: Aloft Downtown Austin $1,999.44 USD
Flight: $626.25 CAD ($494.44 USD) https://www.google.com/travel/flights/s/karjSxt737ityLFk7

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
@iansu Better if you can include details listed here: https://github.com/openjs-foundation/cross-project-council/blob/HEAD/project-resources/MEMBER_TRAVEL_FUND.md#requesting-travel-funds

**Comment by iansu** [comment]
@WaleedAshraf Added everything I can think of. Let me know if I'm missing anything.

**Review by eemeli — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by WaleedAshraf — APPROVED** [review]

**Comment by iansu** [comment]
Updated with final amounts

**Pull request merged**
