### PR TITLE
Project and logo hygiene

### PR DESCRIPTION
**Pull request by brianwarner**
Per discussion in the CPC call, I've connected with the libuv maintainers. The project's
onboarding was never fully completed, and they have opted to not continue with the process. This
commit updates the project list to reflect this.

Signed-off-by: Brian Warner <brian@bdwarner.com>

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by eemeli — APPROVED** [review]

**Comment by eemeli** [comment]
Presumably openjs-foundation/project-status#18 should also be closed?

**Comment by brianwarner** [comment]
I think that makes sense, @eemeli. I'll post a comment and close it.

**Comment by ljharb** [comment]
We can just close it as part of this PR by adding "closes https://github.com/openjs-foundation/project-status/issues/18" to the OP.

**Review by christian-bromann — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by joesepi — APPROVED** [review]

**Pull request merged**
