### PR TITLE
Update project charter template

### LINKED ISSUE #1069: Check, validate, and update, example links in project charter template
I'm [told](https://github.com/nodejs/TSC/issues/1379) the Node.js TSC charter is not a good example to follow today for new project looking to establish a charter (for some sections).

Can the TSC plan to review the project charter template?

I imaigne we would need to:
- Check what sort of suggestions are being made for each section
- Validate that the examples for each section are good examples
- Update the example links where the current example links are not good today

I'm happy to try and facilitate some of this work if the CPC feel it's worthwhile.
I feel it would be great to make onboarding smoother for other proejcts where possible.

### PR DESCRIPTION
**Pull request by tobie**
- Add known project charters to README
- Change examples for guiding principles of project charters

Closes #1069.

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
LGTM. Thanks @tobie!! 🙌

**Comment by ljharb** [comment]
If you want a simpler example of a charter for a smaller project, https://github.com/nvm-sh/nvm/blob/master/PROJECT_CHARTER.md

**Review by ovflowd — APPROVED** [review]

**Comment by tobie** [comment]
> If you want a simpler example of a charter for a smaller project, https://github.com/nvm-sh/nvm/blob/HEAD/PROJECT_CHARTER.md

Yeah, unfortunately it has the same language copy/pasted from Node in the guiding principles section.

**Comment by ljharb** [comment]
Fair, but hmm - in that case it's not clear to me what changes i need to make to that document :-( (or whether i need approval beyond my own)

**Comment by tobie** [comment]
> Fair, but hmm - in that case it's not clear to me what changes i need to make to that document :-( (or whether i need approval beyond my own)

Having gone through a number of projects yesterday in order to find good examples of guiding principles in charters, I can attest that _having_ a charter isn't as common as one would imagine, and is already quite a great step in and of itself. I wouldn't sweat fixing that language for now if I was you. That said, if you wanted to, you'd have to run the output by the CPC according to process. 🤷

**Comment by tobie** [comment]
> Thanks, but I mean, I still don't see what needs fixing. What's inaccurate about it now?

Currently, _Section 0: Guiding Principles_ mostly describes the guiding principles of the foundation. It should instead describe those of the project, as the [prompt](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_CHARTER_TEMPLATE.md#section-0-guiding-principles-optional) suggests:

> _directions: provide a concise, high-level statement about the project's long-term principles, values, or mission._

I've generally found valuable principles to be those that help you make decisions when you have conflicting requirements. For example (this is made up, I don't know if that's what you're about at all!):

> `nvm` aims to be the easiest way to manage multiple node.js versions safely.

So if you suddenly have a design decision to make that pits performance against usability, or ease of use against security, it's easier for you to make the call and anchor your decision in to your principles.

A good example of an actionable guideline is W3C's priority of constituencies (that I [talk and provide resources about here](https://speaking.unlockopen.com/rfBLQk/does-open-source-need-its-own-priority-of-constituencies)).

I hope this helps.

**Review by Relequestual — APPROVED** [review]

**Comment by Relequestual** [comment]
Thanks Tobie!

> Having gone through a number of projects yesterday in order to find good examples of guiding principles in charters, I can attest that _having_ a charter isn't as common as one would imagine...

I had sure hoped there would be more!

Could it be worth adding an explanation as to why so many of the projects do not have a charter when it's a requirement for new projects?

**Comment by tobie** [comment]
I'd rather get the potholes fixed than add a "potholes ahead" signpost, personally.

**Comment by ljharb** [comment]
@Relequestual that info would only be helpful to the CPC (who already knows it) and the very very rare case that a potential project maintainer does the exhaustive research you have, which isn’t something anyone seems to have done before, and imo likely won’t since :-)

**Comment by Relequestual** [comment]
> @Relequestual that info would only be helpful to the CPC (who already knows it) and the very very rare case that a potential project maintainer does the exhaustive research you have, which isn’t something anyone seems to have done before, and imo likely won’t since :-)

@ljharb I'd challenge that. The CPC evolves, people come and go. I did not know this.

I'm also pretty sad it looks like I've done "exhaustive research". I was looking for good examples and couldn't find many. There's a table with gaps in it. I presumed someone just forgot to fill in the gaps.

**Comment by ljharb** [comment]
Fair points.

**Pull request merged**
