### PR TITLE
Added information on how to request support for LF IT managed services.

### PR DESCRIPTION
**Pull request by bensternthal**
This PR adds documentation on how to request support for LF IT managed services. @vvalderrv for visibility.

### CODE REVIEW

**Comment by bensternthal** [comment]
@tobie @mcollina @ljharb  Hi, I am hoping y'all could review this one so I can merge.

**Review by ljharb — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by mhdawson** [comment]
Overall looks good and can land as is. One thing I would wish for is some kind of commitment on a response time but we can see how it goes.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by sheplu — APPROVED** [review]
LGTM

**Review by mertcanaltin — APPROVED** [review]
LGTM

**Pull request merged**
