### PR TITLE
Make link-checker only a cron job

### PR DESCRIPTION
**Pull request by tobie**
Checking all links on pull requests adds unnecessary churn to a substantial ratio of pull requests for very little added benefits.

Let's move to a cron job and remove until someone takes the time to set that up.

### CODE REVIEW

**Comment by ljharb** [comment]
I don't think we need to remove it - it can be made a cron by changing the "on" lines.

**Comment by Trott** [comment]
> I don't think we need to remove it - it can be made a cron by changing the "on" lines.

I think `on` stays but `push` and `pull_request` go. Leave `schedule` and `workflow_dispatch`. Before:

```yaml
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
```

After:

```yaml
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  ```

**Comment by tobie** [comment]
Right, but does't the cron need to _do_ something once it runs (e.g. file an issue)?

**Comment by ljharb** [comment]
No, it merely failing will send a notification to anyone with Write access to the repo.

**Comment by sheplu** [comment]
If you want another type of notification, I guess you can add / link after the fetch a simple message on slack (in a specific channel) or just have the script create an issue and then someone can pick it up and fix it .

But other than that +1 with Trott. Maybe this is not needed on a daily basis, and weekly is enough?  `0 0 * * 1`

**Review by ljharb — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]

**Pull request merged**
