### PR TITLE
Removed Travel Fund Information & Replace With Link To Newer Repo

### PR DESCRIPTION
**Pull request by bensternthal**
This PR removes travel fund information and points folks to the newer repo located [here](https://github.com/openjs-foundation/community-fund/blob/main/programs/travel-fund/index.md).

Once this is merged, three important things come to mind.

1. There is a pending PR https://github.com/openjs-foundation/cross-project-council/pull/1035 with a request that will need to be moved into the new repo
2. We want to ensure folks are aware of and watching that repo for new travel fund requests
3. We should socialize the new asana form to people that have an approved request

### CODE REVIEW

**Comment by ovflowd** [comment]
What about the project funding? Will it also be moved there?

**Comment by bensternthal** [comment]
I think that's the intent @joesepi might have more context.

**Comment by joesepi** [comment]
> What about the project funding? Will it also be moved there?

What do you mean by "project funding" @ovflowd?
Are you referring to this: https://github.com/openjs-foundation/cross-project-council/blob/main/project-resources/PROJECT_FUND.md

If so, I think that will remain where it is. We created the Community Fund repo to track different funding opportunities as outlined (though perhaps not fully outlined) here: https://github.com/openjs-foundation/community-fund/blob/main/README.md

**Comment by christian-bromann** [comment]
> 1. There is a pending PR [chore(travel-expenses): open source summit na - Christian Bromann #1035](https://github.com/openjs-foundation/cross-project-council/pull/1035) with a request that will need to be moved into the new repo

Done: https://github.com/openjs-foundation/community-fund/pull/15

**Pull request merged**
