### PR TITLE
doc: add gov for first term of voting members

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/openjs-foundation/cross-project-council/pull/176

### CODE REVIEW

**Comment by eemeli** [comment]
Other relevant issue: #214

**Comment by mhdawson** [comment]
Happy to be more conservative and change to march 31

**Comment by mhdawson** [comment]
@eemeli updated.

**Comment by kborchers** [comment]
I don't think setting voting member terms based on when a conference takes place is a good idea. I think dates should be set and then if the transition can happen before an event where a meeting will take place, that's great. Otherwise, elections should still happen and the CPC continues to function without being beholden to some conference date that can and will likely change due to many factors out of our control.

**Comment by eemeli** [comment]
Just to clarify, I do agree that we should not be beholden to the whims and vagaries of inconstant conference dates. But I do think that we should not make it more difficult to organise a potential European collab summit next year, or in subsequent years.

My point isn't about the timing of any specific conference, but about the fact that there aren't many in late May or June while there are plenty in April and early May. Next year is not really special in this regard. So, if the CPC terms ends on 31 March, it's much easier to organise a Spring collab summit. If it ends on 30 April, it's more difficult.

**Comment by kborchers** [comment]
I should also clarify that I am fine with the March 31 date as well so I think we are on the same page with that. :)

FWIW, to travel to Europe for an event in the spring, I would likely need to know it was happening by the beginning of the year to be able to plan from both work and personal schedule perspectives. Not sure if others need as much lead time but in general, I usually can't get approvals, etc with only a month or two especially since I am not filling this role as part of my job so I either have to find a way to tie work-related travel to the trip or take vacation time.

**Comment by mhdawson** [comment]
Agreed we could land this in the CPC meeting today. Landing

**Pull request merged**
