### PR TITLE
travel request - from BR to IE - NodeConf EU 22

### PR DESCRIPTION
**Pull request by ErickWendel**
- **Event**: [NodeConf EU 22](https://nodeconf.eu/) + CollabSummit
- **Location**: The Lyrath Estate, Kilkenny, Ireland, **Dates**: September 30 - October 6, **Travelling from**: São Paulo - Brazil 
- **Flight**: [SkyScanner](https://www.skyscanner.com.br/transport/flights/saoa/dub/220930/221006/config/11952-2209301605--32480-1-11154-2210011015|11154-2210061900--32480-1-11952-2210070545?adultsv2=1&cabinclass=economy&childrenv2=&inboundaltsenabled=false&outboundaltsenabled=false&preferdirects=false&rtn=1) - $1689,50 (average from $1,571 - $1,808)
- **Transportation**: [Dublin to Killkenny](https://www.irishrail.ie/en-ie/Offer/webfares) - €18
- **Hotel**: [Kilford Arms](https://www.booking.com/Share-kg7HeM) - $280
- **Hotel**: [Jacobs Inn Hostel](https://www.booking.com/Share-uaR3oE) - $287
- **Event Ticket**: $679.15 (with Matteo's discount for collaborators)
- **Total**: $2953,59
  
@openjs-foundation/cpc

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by Trott** [comment]
Hi, @ErickWendel! I'll be delighted to support your request, but can you please add some info in a comment here?

From https://github.com/openjs-foundation/cross-project-council/blob/5dbeffcbe2a742efbcab8bf179cc81591462174b/project-resources/MEMBER_TRAVEL_FUND.md#requesting-travel-funds: 

> In the pull request description, explain how you calculated your stipend. For example, include estimates for airfare, hotel, other transportation, and so on. The total amount should be your stipend request.

I'm not seeing the breakdown of expenses. Can you add that in a PR comment or point me to where it is that I've missed?

**Comment by ErickWendel** [comment]
> Hi, @ErickWendel! I'll be delighted to support your request, but can you please add some info in a comment here?
> 
> From https://github.com/openjs-foundation/cross-project-council/blob/5dbeffcbe2a742efbcab8bf179cc81591462174b/project-resources/MEMBER_TRAVEL_FUND.md#requesting-travel-funds:
> 
> > In the pull request description, explain how you calculated your stipend. For example, include estimates for airfare, hotel, other transportation, and so on. The total amount should be your stipend request.
> 
> I'm not seeing the breakdown of expenses. Can you add that in a PR comment or point me to where it is that I've missed?

Uh, sorry about that! Just updated it!

**Comment by ErickWendel** [comment]
> Hi, @ErickWendel! I'll be delighted to support your request, but can you please add some info in a comment here?
> 
> From https://github.com/openjs-foundation/cross-project-council/blob/5dbeffcbe2a742efbcab8bf179cc81591462174b/project-resources/MEMBER_TRAVEL_FUND.md#requesting-travel-funds:
> 
> > In the pull request description, explain how you calculated your stipend. For example, include estimates for airfare, hotel, other transportation, and so on. The total amount should be your stipend request.
> 
> I'm not seeing the breakdown of expenses. Can you add that in a PR comment or point me to where it is that I've missed?

Uh, sorry about that! Just updated with the final amount for the Collab and NodeCounf EU events

**Comment by Trott** [comment]
@ljharb Can you reiterate (or withdraw) your approval now that the amount has been updated?

**Comment by Trott** [comment]
@openjs-foundation/cpc

**Review by Trott — APPROVED** [review]

**Review by ljharb — APPROVED** [review]
wow, the event's more expensive than i expected

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Trott** [comment]
@openjs-foundation/cpc-voting-members This needs at least one more approval.

**Review by dylans — APPROVED** [review]

**Review by timmywil — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]

**Comment by ErickWendel** [comment]
Hey folks. I'm sorry for letting you know in some short notice but I won't be able to attend those events anymore. Should I rollback my PR?

**Comment by ljharb** [comment]
@ErickWendel yep, click the "revert" button and we'll land that. thanks for following up!

**Comment by ErickWendel** [comment]
> @ErickWendel yep, click the "revert" button and we'll land that. thanks for following up!

I don't think I can do it by just clicking here.

I got the msg: "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged. "

**Comment by ljharb** [comment]
ah ok, same. i guess manually removing the line would work then?

**Comment by ErickWendel** [comment]
Just added it there: https://github.com/openjs-foundation/cross-project-council/pull/939

**Pull request merged**
