### PR TITLE
[CHORE] Broken Link Fix

### LINKED ISSUE #735: Staging Process doc link broken in README.md
In [section - Policy Change Proposal Process](https://github.com/openjs-foundation/cross-project-council#policy-change-proposal-process), the link to **staging process** doc is broken. opens a 404 page.

### PR DESCRIPTION
**Pull request by jorydotcom**
Closes #735

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
Thanks!

**Review by SaraJo — APPROVED** [review]
LGTM

**Review by ljharb — APPROVED** [review]
fast track?

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by marsonya — APPROVED** [review]

**Pull request merged**
