### PR TITLE
Add Regular Member voting and clarify At large term

### PR DESCRIPTION
**Pull request by joesepi**
It seems that the regular member voting election isn't in this list. 🤔 

Also, I believe we discussed removing the "non-Impact" term in favor of At-Large since we removed the Growth designation a while ago.

Signed-off-by: Joe Sepi <sepi@joesepi.com>

### CODE REVIEW

**Review by eemeli — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ljharb — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgt

**Review by ovflowd — COMMENTED** [review]
:shipit:

**Review by tobie — COMMENTED** [review]
@joesepi wrote:
> I believe we discussed removing the "non-Impact" term in favor of At-Large since we removed the Growth designation a while ago.

My understanding is we're doing some back and forth on that depending on whether we're thinking about being inclusive to incubating projects or clear that growth status is no longer a thing.

**Review by tobie — APPROVED** [review]

**Review by dylans — APPROVED** [review]

**Review by ovflowd — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
