### PR TITLE
Add Sendil to regular members list

### PR DESCRIPTION
**Pull request by sendilkumarn**
Rebased on top of #222

### CODE REVIEW

**Comment by mhdawson** [comment]
@openjs-foundation/cpc could we get a few more approvals so we can land?

**Comment by mhdawson** [comment]
@sendilkumarn we talked a bit about the process for adding regular members in the last meeting and part of the was to ask what project people are part of so that we can provide an FYI to the project that a member has joined. 

Can you add a comment with the Foundation projects that you are involved in?

**Comment by sendilkumarn** [comment]
> Can you add a comment with the Foundation projects that you are involved in?

**Comment by mhdawson** [comment]
Lots of approvals and no objects >72 hours.  There was some confusion  on whether I should have landed the other regular member PR's but since we've not reverted those I think we should land this one as well.  @openjs-foundation/cpc please comment if you disagree, otherwise I'll plan to land mid next week.

**Comment by MylesBorins** [comment]
landed in c946c85

**Pull request closed without merging**
