### PR TITLE
doc: Add NativeScript to incubating section in README

### PR DESCRIPTION
**Pull request by joesepi**
No need for logo(s) at incubating stage, methinks.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
nvm doesn't have a logo.

**Comment by joesepi** [comment]
Interesting @ljharb -- I saw a "logo" on the openjs foundation website. Is that just a placeholder sort of thing? looks good enough to me. :)
https://openjsf.org/projects/

**Comment by joesepi** [comment]
Maybe we just leave the logos out of the incubating table regardless and then we can just fast track this PR since the announcement was already made.

**Comment by joesepi** [comment]
I'd like to request that we fast track this PR since the announcement has already been made.

In order to fast track, we would need to CPC members to thumbs up this comment and also to have no objections to the fast tracking request.

https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#fast-tracking-prs

**Review by tobie — APPROVED** [review]
LGTM

**Pull request merged**
