### PR TITLE
chore: add Hemanth HM to 2022 travel fund

### PR DESCRIPTION
**Pull request by hemanth**
Sorry for the late PR, there were some challenges with the travel fund and hence this PR is happening now. 

- Name of the event : OpenJS World 2022
- The location, dates of the event and where you will be travelling from: Austin, TX June 6-10 is the event, I shall be traveling from SF.
- The presentation you intend to give: [Standards workshop](https://sched.co/10fNK)
- The size of the stipend you wish to receive:  1500 USD.
- Estimate: 593 (Airbnb) + 753 (flight) + 154 (transport)

//cc @openjs-foundation/cpc

Signed-off-by: hemanth.hm <hemanth.hm@gmail.com>

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by joesepi — APPROVED** [review]

**Comment by hemanth** [comment]
The change in the commit has that, you mean that it would be better mentioned in the comment?

**Comment by WaleedAshraf** [comment]
@hemanth You can add these details in the PR description above.
https://github.com/openjs-foundation/cross-project-council/blob/HEAD/project-resources/MEMBER_TRAVEL_FUND.md#requesting-travel-funds

**Comment by hemanth** [comment]
@WaleedAshraf Thanks, I wasn't aware of the format. I had just referred to previous PRs and had created this. 

P.S: I have updated the description accordingly.

**Comment by ljharb** [comment]
2 approvals and past 72 hours; merging.

**Pull request merged**
