### PR TITLE
Create node-2024-learn-proposal.md

### PR DESCRIPTION
**Pull request by bensternthal**
@ovflowd OK I took your original proposal and converted it into the template format requested by google. There is some information missing.

I called out what was missing in double braces {{ }}.

I do not know enough about the work or the project to fill in these pieces, I am hoping you can.

Note do let me know if you would not have the time to complete this by the deadline. We would need to submit by April 1 (deadline is April 2)

See also https://github.com/openjs-foundation/cross-project-council/issues/1278

### CODE REVIEW

**Comment by ovflowd** [comment]
Hi @bensternthal super extremely appreciate you! Ill give a read whenever I'm able to and Ill let you know if by any chance I feel that finishing this by 1st of April is out of reach 👀

**Comment by ovflowd** [comment]
@bensternthal I've updated the content with the missing parts. Please feel free to review, rephrase or change the affected parts.

I've made a budget, but I need the Foundation's approval since the organization is expected to pay first and then get reimbursed by Google for what I understood.

cc @openjs-foundation/cpc @bensternthal @rginn

**Comment by bensternthal** [comment]
@ovflowd ill take a deeper look Monday. Poking around the [google docs](https://developers.google.com/season-of-docs/docs/org-payments) I did not see any mention of the org paying first.

> Organizations will receive 40% of the grant after hiring a technical writer. Organizations will receive invitations to submit their first expense starting June 11, 2024.

> Organizations  will receive the remaining 60% of the grant after successful completion of the Google Season of Docs program. Organizations will receive invitations to submit their final expense starting December 13, 2024. All successful projects will start to receive final payment on December 13, 2024.

I interpreted the above to imply that we make payments to the writer directly from the funding received from Google. Note I have not run a program like this before, so if I am wrong, let me know.

**Review by Queenkaz — APPROVED** [review]

**Review by Queenkaz — APPROVED** [review]

**Comment by ovflowd** [comment]
> @ovflowd ill take a deeper look Monday. Poking around the [google docs](https://developers.google.com/season-of-docs/docs/org-payments) I did not see any mention of the org paying first.
> 
> > Organizations will receive 40% of the grant after hiring a technical writer. Organizations will receive invitations to submit their first expense starting June 11, 2024.
> 
> > Organizations  will receive the remaining 60% of the grant after successful completion of the Google Season of Docs program. Organizations will receive invitations to submit their final expense starting December 13, 2024. All successful projects will start to receive final payment on December 13, 2024.
> 
> I interpreted the above to imply that we make payments to the writer directly from the funding received from Google. Note I have not run a program like this before, so if I am wrong, let me know.

Right, I might have misinterpreted the text then, that definitely makes more sense!

**Comment by bensternthal** [comment]
@ovflowd this is good to be merged. Note I do not have permissions to do so :(

**Comment by ovflowd** [comment]
> @ovflowd this is good to be merged. Note I do not have permissions to do so :(

You don't? O.o but you just did 🤔

**Comment by bensternthal** [comment]
I missed the checkbox that allowed me to do so!!

**Pull request merged**
