### PR TITLE
Add sunsetting checklist to PROJECT_PROGRESSION.md

### LINKED ISSUE #715: Create offboarding checklist
This is for moving projects to emeritus status. Belongs in [`PROJECT_PROGRESSION.md`](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md) and as an issue template in [`project-status`](https://github.com/openjs-foundation/project-status).

Relates to https://github.com/openjs-foundation/cross-project-council/issues/713.

### PR DESCRIPTION
**Pull request by tobie**
Closes #715.

### CODE REVIEW

**Review by eemeli — APPROVED** [review]

**Review by codebytere — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by sendilkumarn — APPROVED** [review]
Can we make this part of [this](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/PROJECT_EXIT_CRITERIA) proposal too?

**Comment by tobie** [comment]
> Can we make this part of [this](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/PROJECT_EXIT_CRITERIA) proposal too?

Oh, maybe we should rename the checklist to avoid confusion between leaving the Foundation and moving to Emeritus stage. I'll fix the name here, but wouldn't want to block on solving both processes to move forward with merging this PR.

**Review by joesepi — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
