### PR TITLE
Add Paula Paul as a regular member

### PR DESCRIPTION
**Pull request by PaulaPaul**
Hello!
I've been joining CPC calls for the past several months and more recently have been involved in discussions of the travel fund and Code of Conduct, helping wherever I can. My company (Greyshore) has applied to become a Silver member and I plan to continue forward in the CPC and other Foundation activities. Looking forward to lending a hand-

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by ovflowd — APPROVED** [review]
LGTM! So excited that you're finally doing this :)

**Review by WaleedAshraf — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]

**Comment by PaulaPaul** [comment]
ah, I think the link checker is garging on some references that may be related to the new website. @bensternthal I saw some traffic about broken links being fixed, would you like me to look into the six links that could not resolve from this check or is that work tracked somewhere else? Thanks everyone!

**Review by timmywil — APPROVED** [review]

**Comment by WaleedAshraf** [comment]
@PaulaPaul broken links check should not block your PR from merge. We have tried to fix it multiple times in past. There is a separate issue for it https://github.com/openjs-foundation/cross-project-council/issues/916

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
