### PR TITLE
Update COMMUNITY_FUND_POLICY.md

### LINKED ISSUE #1154: Decide on a scoring rubric to evaluate travel fund requests
In his [proposal](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.fbxtnhs2b9da), @bensternthal suggested for the CPC to adopt a scoring rubric to evaluate travel fund requests.

This has the benefit of reducing bias in the approval process and making it easier to delegate part of the approval process to Foundation staff if needed.

```[tasklist]
### Tasks
- [x] Decide whether the CPC agrees with this recommendation
- [x] Create scoring rubric
- [x] Get CPC consensus about the data that needs to be collected for scoring rubric (shouldn’t be contentious)
- [x] Get CPC consensus about the weights for the scoring rubric (potentially contentious)
```

### PR DESCRIPTION
**Pull request by bensternthal**
Fixes #1154 - documents the current rubric

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by tobie — APPROVED** [review]

**Comment by ljharb** [comment]
looks like someone needs to poke the OSI to unbreak their links :-/

**Comment by tobie** [comment]
> looks like someone needs to poke the OSI to unbreak their links :-/

Email sent.

**Review by joesepi — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by eemeli — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by VoltrexKeyva — APPROVED** [review]

**Pull request merged**
