### PR TITLE
✨ add @ctcpip to CPC members

### PR DESCRIPTION
**Pull request by ctcpip**
👋 

folks looking at this PR probably know me from:

- CPC meetings
- OpenJS standards meetings
- OpenJS security meetings
- elsewhere?

🙏

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by marco-ippolito — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
Oh yeah! :partying_face:

**Review by WaleedAshraf — APPROVED** [review]

**Comment by ljharb** [comment]
@WaleedAshraf this was merged too soon; the governance doc says non-fast-tracked PRs must be open for 72 hours.

**Comment by WaleedAshraf** [comment]
@ljharb Ops. Sorry, I thought it was 48 hours. Would you like me to revert it?

**Comment by ljharb** [comment]
No, let's leave it here unless someone objects.

**Pull request merged**
