### PR TITLE
TLDR for collab spaces

### PR DESCRIPTION
**Pull request by joesepi**
I've had folks mention to me on a number of occasions that they dont understand how a collab space differs from a working group.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by tobie** [comment]
The thing is _we_ also have working groups.

**Comment by joesepi** [comment]
We shouldn't have working groups. We should convert Standards WG to a Collab Space. Unify around collab

**Comment by tobie** [comment]
To me the the confusion arises because we have both, not because other orgs have WG and we call them something else (other orgs have SIGs, IGs, TFs, etc.; do we need to also explain how each one of those is different?)

I think that this PR will add confusion until we merge WGs and Collab Spaces together, and that it’ll become moot afterwards. I won’t block if others feel differently, however.

**Comment by joesepi** [comment]
>I think that this PR will add confusion until we merge WGs and Collab Spaces together, and that it’ll become moot afterwards. I won’t block if others feel differently, however.

I fully agree @tobie -- I opened this issue to discuss and we should hold off on this PR until we've figured out how we want to move forward. Thanks!

**Review by darcyclarke — APPROVED** [review]

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by tobie** [comment]
Closed in favor of https://github.com/openjs-foundation/cross-project-council/issues/1110.

**Pull request closed without merging**
