### PR TITLE
Add myself to regular members list

### PR DESCRIPTION
**Pull request by mikesamuel**
I contribute and attend meetings on a regular basis so best to make it semi-official.

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
🎉

**Review by christian-bromann — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Comment by mikesamuel** [comment]
The lint failure seems unrelated:

```
Error: [0] http://civs.cs.cornell.edu/
Error: [0] https://civs.cs.cornell.edu/
Scanned total of 1167 links!
Error: Detected 2 broken links.
```

Those links look legit dead.  Maybe linking to https://github.com/andrewcmyers/civs in the meantime would make sense.

**Comment by ljharb** [comment]
Filed https://github.com/andrewcmyers/civs/issues/53

**Review by tobie — APPROVED** [review]

**Review by eemeli — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by joesepi** [comment]
This can be merged tomorrow. Let's be sure to follow the additional steps outlined here: https://github.com/openjs-foundation/cross-project-council/blob/HEAD/GOVERNANCE.md#approving-and-onboarding-regular-members

(this is partially a note-to-self, if I am the one merging. :)

**Comment by joesepi** [comment]
@mikesamuel -- welcome to the team! 🎉 

I've added you to the github team and added you to the directory but can you please update details in this directory pull request? https://github.com/openjs-foundation/directory-private/pull/20
(that PR is private so you wont see it until you accept your invitation to the github team)

Cheers!

**Pull request merged**
