### PR TITLE
added @waleedashraf as member

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Adding my self as a member. As being a member of the Node.js Foundation for almost 2 years. 🎉 ❤️ 
Looking forward to participating in openjs-foundation and CPC work.

### CODE REVIEW

**Comment by mhdawson** [comment]
As per https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#approving-and-onboarding-regular-members looks ready to land (3 voting members who approved are @mcollina, @dmethvin, @eemeli)

**Comment by mhdawson** [comment]
Notification to Node.js reps complete, landing

**Comment by mhdawson** [comment]
@joesepi  I don't seem to have access to add him to cpc-regular-members.  I think we had agreed to give regular members org ownership so can you either do that for me or add Waleed to the regular members team?

**Comment by joesepi** [comment]
I've added @WaleedAshraf to the cpc-regular-members team, @mhdawson. Thanks

**Pull request merged**
