### PR TITLE
chore(members): add evenstensberg

### PR DESCRIPTION
**Pull request by evenstensberg**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
@evenstensberg for future reference, governance is that a PR must be open for 72 hours before merging.

**Comment by evenstensberg** [comment]
Gotcha

**Comment by joesepi** [comment]
@evenstensberg there are a number of issues with this PR having been merged:

- the 72hr requirement unless fast tracked like @ljharb said above
- there should be at least two approvers on a PR before merging
- the member list is alphabetical and this PR breaks that

**Comment by evenstensberg** [comment]
So sorry @joesepi . You can revert this PR and I'll submit a new one. Again, sorry!

**Comment by joesepi** [comment]
> So sorry @joesepi . You can revert this PR and I'll submit a new one. Again, sorry!

@evenstensberg -- Its not really a big deal at all, so no worries. I just wanted to share all that was at issue for awareness.

I'll just fix the alphabetizing in a new PR and fast track it. :)

**Pull request merged**
