### PR TITLE
add Nitin Kumar as a regular member

### PR DESCRIPTION
**Pull request by snitin315**
I've been active in the development and maintenance of the [webpack](https://webpack.js.org/) & [ESLint](https://eslint.org/) projects for the last 3-4 years.

- Contributions to [ESLint](https://github.com/eslint/eslint/pulls?q=+is%3Apr+author%3Asnitin315+)
- Contributions to [webpack](https://github.com/webpack/webpack/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack-cli](https://github.com/webpack/webpack-cli/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack-dev-server](https://github.com/webpack/webpack-dev-server/pulls?q=+is%3Apr+author%3Asnitin315+), [webpack.js.org](https://github.com/webpack/webpack.js.org/pulls?q=+is%3Apr+author%3Asnitin315+)

### CODE REVIEW

**Review by evenstensberg — APPROVED** [review]

**Comment by joesepi** [comment]
Hello @snitin315 - Its great that you are interested in joining the Cross Project Council. We would be happy to have you.

You may not be getting much response to this PR because it is lacking any context. As it says in our [README](https://github.com/openjs-foundation/cross-project-council#regular-members) and [Governance](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#approving-and-onboarding-regular-members), you should share more information about yourself and your efforts within the foundation or a foundation hosted project:
>Regular members can self-nominate by opening a PR to add themselves to the Regular member list in the [README.md](https://github.com/openjs-foundation/cross-project-council/blob/main/README.md). The PR should include information about how the potential new member has been active in the foundation or its member projects as described below in the [Active OpenJS Collaborator](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#definition-of-an-active-openjs-collaborator) section of this document.

Please update this PR description with this info and I'm sure that will help move this along. We'd be happy to have you involved!

**Comment by snitin315** [comment]
Hi @joesepi, thanks for the review. I've updated the PR description as requested.

**Review by ljharb — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by joesepi — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]

**Review by WaleedAshraf — APPROVED** [review]

**Comment by joesepi** [comment]
Welcome @snitin315! 🎉

**Pull request merged**
