### PR TITLE
chore: add Michaela Laurencin as Electron CPC Voting Member

### PR DESCRIPTION
**Pull request by mlaurencin**
Hi, I would like to request that I be added as the new CPC Voting Member for Electron. I have been a maintainer on the project for the past few years now. I'm looking forward to attending meetings and working with all of you.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
assuming electron folks stamp

**Review by jkleinsc — APPROVED** [review]
Approving for Electron

**Review by tobie — APPROVED** [review]
Welcome!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by christian-bromann — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
Welcome

**Review by erickzhao — APPROVED** [review]

**Review by rxmarbles — APPROVED** [review]

**Pull request merged**
