### PR TITLE
Travel fund request: Unicode Conference, 13-16 October

### PR DESCRIPTION
**Pull request by eemeli**
This is a travel fund request for participating at this year's Internationalization & Unicode Conference, and speaking there about the work being done in the Unicode MessageFormat Working Group.

I am the Foundation's representative to that working group, and a maintainer of the `messageformat` project. I have attempted to have my travel costs covered by my employer, but this is not currently possible due to their travel policy not supporting travel outside my home country (Finland).

I'm asking for 800 USD, which is an estimate of the cost of my flights (Chicago -> San Francisco -> Helsinki) and transits to and from airports. I have already made other arrangements covering my ticket for the conference, for accommodations while there, and for travel up to Chicago; this would be an extension of a personal trip.

Edit: Forgot to add earlier the @openjs-foundation/cpc mention.

### CODE REVIEW

**Review by Trott — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by jorydotcom — APPROVED** [review]

**Comment by jorydotcom** [comment]
go get 'em, @eemeli !!

**Review by dylans — APPROVED** [review]
My only comment is that you've done an amazing job to keep foundation expenses to a minimum by adding this to a personal trip, so if it turns out to be more expensive than estimated, we should try to approve that as well.

**Review by mhdawson — APPROVED** [review]
LGTM and thanks!

**Comment by eemeli** [comment]
Merging, as this fulfills the other [approval criteria](https://github.com/openjs-foundation/cross-project-council/blob/main/project-resources/MEMBER_TRAVEL_FUND.md#approval) and I need to book my flights. 🛫

**Comment by bnb** [comment]
already merged but here's my belated enthusiastic +1

**Pull request merged**
