### PR TITLE
feat(travel-fund): updated travel-fund to 2023

### PR DESCRIPTION
**Pull request by ovflowd**
This PR archives the 2022 travel fund and creates the 2023 one.

### CODE REVIEW

**Comment by anonrig** [comment]
Can we remove the changes done on the package-lock.json?

**Comment by ovflowd** [comment]
> Can we remove the changes done on the package-lock.json?

For any specific reason? There's one high-related CVE, I know it's not exactly the scope of the said-PR, but it's such a diminishing change that I don't see why not keeping it.

**Review by anonrig — APPROVED** [review]

**Comment by ovflowd** [comment]
Thanks, @anonrig, appreciate it! I know usually we'd like to keep PR's specifically on-topic, I just really wanted to avoid making a PR just for that silly little thingy 🙈

**Review by erickzhao — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Comment by mhdawson** [comment]
@SaraJo, @mcollina can you confirm as the board representatives that the budget for the travel fund was retained for 2023 and is the same amount? I assume it was but standard practice is to confirm with the board reps.

**Review by christian-bromann — APPROVED** [review]

**Comment by ovflowd** [comment]
Hey all, after checking with the @openjs-foundation/cpc on today's meeting, we're going to proceed with merging this for now, and have a `tbd` of what the actual budgets are :)

**Comment by ovflowd** [comment]
_Linkinator is failing but not due a changed from this PR, so proceeding with merge_

**Comment by SaraJo** [comment]
> @SaraJo, @mcollina can you confirm as the board representatives that the budget for the travel fund was retained for 2023 and is the same amount? I assume it was but standard practice is to confirm with the board reps.

Can confirm, it is the same amount.

**Pull request merged**
