### PR TITLE
Add mmarchini as a regular member

### PR DESCRIPTION
**Pull request by mmarchini**
I've been active on Node.js for a few years, I'm starting to familiarize myself more with the work the CPC does and I would like to get more involved.

### CODE REVIEW

**Comment by designMoreWeb** [comment]
LGTM

**Comment by MylesBorins** [comment]
@designMoreWeb I appreciate the enthusiasm to land this but according to our governance this PR was supposed to be left open for at least a week before landing (among a few other pieces of due diligence)

https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#approving-and-onboarding-regular-members

**Comment by MylesBorins** [comment]
@openjs-foundation/cpc I think that we need to revert this PR and open a new one to add @mmarchini to the CPC. To be clear I'm beyond enthusiastic to have her participate in the group, but want to ensure we are properly following our existing documented process.

FWIW if we feel the existing process is to cumbersome we can totally augment it to allow for faster turnaround

**Comment by designMoreWeb** [comment]
> @designMoreWeb I appreciate the enthusiasm to land this but according to our governance this PR was supposed to be left open for at least a week before landing (among a few other pieces of due diligence)
> 
> https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#approving-and-onboarding-regular-members

I was excited to have @mmarchini on the CPC and i got a little too enthusiastic and lost track of the wait time. Thank you for pointing out @MylesBorins

**Comment by MylesBorins** [comment]
@designMoreWeb no worries at all! These things happen.

I went ahead and force pushed master to remove the commit... @designMoreWeb would you like to take the action item of opening a new PR?

**Comment by designMoreWeb** [comment]
> @designMoreWeb no worries at all! These things happen.
> 
> I went ahead and force pushed master to remove the commit... @designMoreWeb would you like to take the action item of opening a new PR?

Sure i will take care of the action item of opening the new PR and i will link this to that one so members are aware of why we needed to open a new one

**Comment by designMoreWeb** [comment]
@MylesBorins Have created the [new PR](https://github.com/openjs-foundation/cross-project-council/pull/612)

**Pull request merged**
