### PR TITLE
doc: update link for Node.js CoC link

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/nodejs/node/pull/41408

The code-of-conduct.md file has been moved, update
the related links.

Signed-off-by: Michael Dawson <mdawson@devrus.com>

DO NOT Land until  https://github.com/nodejs/node/pull/41408 lands

### CODE REVIEW

**Review by joesepi — APPROVED** [review]
Thanks!

**Comment by joesepi** [comment]
This should also fix our failing tests...

**Comment by mhdawson** [comment]
I think we should fast track this

**Comment by mhdawson** [comment]
I guess I need to rebase

**Pull request merged**
