### PR TITLE
doc: remove duplicate checklist

### PR DESCRIPTION
**Pull request by MylesBorins**
This removes the duplicated checklist in the issue template and
instead links to the checklist in the new project application

Fixes: #288

### CODE REVIEW

**Comment by MylesBorins** [comment]
@jorydotcom I know you had mixed feelings about landing this change. Happy to close it just lmk

**Comment by tobie** [comment]
Curious why you don't do that the other way round (i.e., keep the checklist in the issue template).

**Comment by MylesBorins** [comment]
@tobie the issue template is in a hidden directory `.github` and not super discoverable for folks aside from when the issue is created.

**Comment by tobie** [comment]
Fair enough.

**Comment by kborchers** [comment]
Hmm, I definitely agree with removing the duplication but I think it makes more sense for the list to live in the template where it will actually be used and then we can link to the template from the application for folks to review it when reviewing the application process. Asking folks to copy/paste when creating the application issue sort of defeats the purpose of the template IMO.

If others disagree and we decide to merge this, could we at least update the link to point to [the raw markdown](https://raw.githubusercontent.com/openjs-foundation/cross-project-council/master/NEW_PROJECT_APPLICATION.md) so that people can easily copy the list and paste it into the issue? Otherwise, it adds a step for people to find what they actually have to copy and could also lead to lists copied from the rendered HTML which isn't useful.

**Comment by mcollina** [comment]
I don't see a big problem with the duplication, we are likely not updating this very often.

**Comment by mhdawson** [comment]
My suggestion is to remove the checklist from the proposal doc instead and add a link to the template there.  That way when you create new issue you get the checklist and it is still discoverable through the proposal doc,

**Comment by tobie** [comment]
The other option would be to clearly mark which of the two checklists is the canonical one.

**Comment by MylesBorins** [comment]
I've made two changes.

1. Add onboarding checklist back to template
  - added comment about when it had been copied and where from which should remind people to update
2. I've moved the onboarding checklist from `./NEW_PROJECT_APPLICATION.md` to `./PROJECT_PROGRESSION.md` 

One thing to keep an eye out for... it seems like the copy from the application and the issue are already out of sync. Which version is canonical?

**Comment by MylesBorins** [comment]
I plan to land this after today's meeting if there are no objections

**Pull request merged**
