### PR TITLE
Add Jean Burellier as regular member

### PR DESCRIPTION
**Pull request by sheplu**
Hello 👋 I would kindly request to be a regular member. I have been part to a few WG in Node.js in the past few years (Next-10, Web-Server-Framework mostly) while (co)chairing a few deep dive. I am also participating in some other projects, like Express.

I have been attending / following some of the latest CPC meetings and Working Session

### CODE REVIEW

**Review by rxmarbles — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
Big +1!

**Review by tobie — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by joesepi — APPROVED** [review]

**Review by VoltrexKeyva — APPROVED** [review]
Welcome aboard!

**Review by timmywil — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by christian-bromann — APPROVED** [review]

**Comment by sheplu** [comment]
seems like there is a missing file that was removed :D

**Comment by tobie** [comment]
Opened a PR here to fix the broken link issue: https://github.com/openjs-foundation/cross-project-council/pull/1266

**Review by Ethan-Arrowood — APPROVED** [review]

**Pull request merged**
