### PR TITLE
Travel Fund - Stage 3

### PR DESCRIPTION
**Pull request by Jonahss**
Previous PR: https://github.com/openjs-foundation/cross-project-council/pull/283

In the README for this proposal, I attempted to answer the last "unresolved question", clarifying who qualifies for use of the fund:
>Who qualifies for using the Travel Fund?
>As the document currently states:
>>* Candidates must be an active participant of one of the projects of the OpenJS Foundation.
>>* Those requesting funds must indicate that they do not have funding available from another source, such as an employer or the event itself that might cover costs for presenters.
>
>This means, any project in the Foundation, no matter the level.
For each project, any active participant is welcome to apply for funds. This would mean any contributor or someone active in the community. Their participation should be self-evident (github activity, etc), and if in doubt their project representative can be asked to confirm.
 
Also, @brianwarner, did you create `visainfo@openjsf.org` and `travelapprovals@openjsf.org`?

All the other TODOs involve getting links to line up in the new repo and such, which can be done in the next PR.

I've been out of town a lot and have missed several meetings, do I still need to gather more info on predicted future use? Or are people feeling less worried about that.

### CODE REVIEW

**Comment by MylesBorins** [comment]
This PR should likely move the various documents to the root of the repository

**Comment by Jonahss** [comment]
Okay. Sorry for the delay, organized a large wedding.

**Comment by joesepi** [comment]
Consensus is (from talking about it at a couple CPC meetings) is that this should be taken to the board for approval to continue moving it forward in our staging process.

**Comment by Jonahss** [comment]
Cool!
When all is ready I can set up the last PR for merging things into the main repo in their proper places.

**Comment by mhdawson** [comment]
Believe this needs Board review since it has a delegated budget.  I have sent request for review to the Board.

**Comment by mhdawson** [comment]
No concerns from the Board, landing.

**Comment by mhdawson** [comment]
Landed as 54bed25c265dbd365a469dd212d39744053cae7c

**Comment by Jonahss** [comment]
I'll set up the PR for final merging of this proposal in the next 7 days.

**Pull request closed without merging**
