### PR TITLE
Move security reporting proposal to stage 3

### PR DESCRIPTION
**Pull request by MarcinHoppe**
Moving the security reporting proposal to stage 3, per discussion in #326.

The corresponding checklist update: openjs-foundation/project-onboarding#52.

This PR supersedes #602.

### CODE REVIEW

**Review by mikesamuel — APPROVED** [review]

**Review by kborchers — APPROVED** [review]

**Review by timmywil — APPROVED** [review]

**Review by joesepi — APPROVED** [review]

**Comment by MylesBorins** [comment]
Added `board approval required` because that is usually a gate for stage-3. At the very least an FYI seems appropriate. If this has already been discussed and there was consensus we don't need anything from the board please feel free to dismiss

**Comment by MarcinHoppe** [comment]
@MylesBorins I don't think this was ever discussed, so thanks for flagging this PR.

**Comment by mhdawson** [comment]
@Myles I think we'd mentioned that we did not think it needed board approval as its not chaning the charter of the CPC.  Not that I'm opposed. I do think we've mentioned that it was underway already.

**Comment by MylesBorins** [comment]
@mhdawson That seems reasonable to me... I guess if there is no need for board approval then 2 -> 3 should basically be automatic

**Review by tobie — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by mikesamuel — APPROVED** [review]

**Pull request merged**
